events {}

http {
    # DNS interne Docker — résolution à la volée, pas au démarrage
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        # API backend → /api/*
        location /api/ {
            include /etc/nginx/active_color.conf;
        }

        # Frontend → tout le reste
        location / {
            include /etc/nginx/active_color_front.conf;
        }
    }
}
