events {}

http {
    upstream app_blue_back  { server app-back-blue:3000;  }
    upstream app_green_back { server app-back-green:3000; }

    upstream app_blue_front  { server app-front-blue:80;  }
    upstream app_green_front { server app-front-green:80; }

    server {
        listen 80;

        # API backend → /api/*
        location /api/ {
            include /etc/nginx/active_color.conf;
        }

        # Frontend → tout le reste
        location / {
            include /etc/nginx/active_color_front.conf;
        }
    }
}
